# Generated by Django 5.0.6 on 2024-08-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
    ]
