# Generated by Django 5.0.3 on 2024-08-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_testproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestProject',
        ),
    ]
